python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 42 --representation time_window --max-epochs 100 --name time_window_09_42_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 42 --representation spike_count --max-epochs 100 --name spike_count_09_42_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 42 --representation timesurface --max-epochs 100 --name timesurface_09_42_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 13 --representation time_window --max-epochs 100 --name time_window_09_13_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 13 --representation spike_count --max-epochs 100 --name spike_count_09_13_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 13 --representation timesurface --max-epochs 100 --name timesurface_09_13_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 93 --representation time_window --max-epochs 100 --name time_window_09_93_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 93 --representation spike_count --max-epochs 100 --name spike_count_09_93_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 93 --representation timesurface --max-epochs 100 --name timesurface_09_93_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 45 --representation time_window --max-epochs 100 --name time_window_09_45_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 45 --representation spike_count --max-epochs 100 --name spike_count_09_45_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 45 --representation timesurface --max-epochs 100 --name timesurface_09_45_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 96 --representation time_window --max-epochs 100 --name time_window_09_96_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 96 --representation spike_count --max-epochs 100 --name spike_count_09_96_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 96 --representation timesurface --max-epochs 100 --name timesurface_09_96_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 6 --representation time_window --max-epochs 100 --name time_window_09_6_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 6 --representation spike_count --max-epochs 100 --name spike_count_09_6_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 6 --representation timesurface --max-epochs 100 --name timesurface_09_6_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 98 --representation time_window --max-epochs 100 --name time_window_09_98_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 98 --representation spike_count --max-epochs 100 --name spike_count_09_98_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 98 --representation timesurface --max-epochs 100 --name timesurface_09_98_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 59 --representation time_window --max-epochs 100 --name time_window_09_59_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 59 --representation spike_count --max-epochs 100 --name spike_count_09_59_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 59 --representation timesurface --max-epochs 100 --name timesurface_09_59_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 44 --representation time_window --max-epochs 100 --name time_window_09_44_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 44 --representation spike_count --max-epochs 100 --name spike_count_09_44_8 --batch-size 8
python3 extended_script.py --train-data-size 0.9 --val-data-size 0.1 --random-seed 44 --representation timesurface --max-epochs 100 --name timesurface_09_44_8 --batch-size 8
